CREATE DATABASE pernasSolidarias;

CREATE TABLE CORREDOR(
    CD_CORREDOR INT AUTO_INCREMENT PRIMARY KEY,
    NM_CORREDOR VARCHAR(255),
    CPF VARCHAR(15),
    TAM_CAMISA VARCHAR(10),
    DT_NASCIMENTO DATE 
);

CREATE TABLE CADEIRANTE(
    CD_CADEIRANTE INT AUTO_INCREMENT PRIMARY KEY,
    NM_CADEIRANTE VARCHAR(255),
    CPF VARCHAR(15),
    TAM_CAMISA VARCHAR(10),
    DT_NASCIMENTO DATE
);

CREATE TABLE EVENTO(
    CD_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
    NM_EVENTO VARCHAR(255),
    DISTANCIA FLOAT,
    DT_EVENTO DATE
);

CREATE TABLE PARTICIPACAO_EVENTO(
    CD_PARTICIPACAO_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
    CD_CADEIRANTE INT,
    CD_CORREDOR INT,
    CD_EVENTO INT,
    FOREIGN KEY (CD_CADEIRANTE) REFERENCES CADEIRANTE(CD_CADEIRANTE),
    FOREIGN KEY (CD_CORREDOR) REFERENCES CORREDOR(CD_CORREDOR),
    FOREIGN KEY (CD_EVENTO) REFERENCES EVENTO(CD_EVENTO)
);